# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
env:
  GIN_MODE: release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Revive Action
      uses: morphy2k/revive-action@v2.4.1

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
